//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Há um cadastro ativo com este CPF.
        /// </summary>
        public static string CPFAlreadyRegistered {
            get {
                return ResourceManager.GetString("CPFAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} é obrigatório.
        /// </summary>
        public static string FieldIsMandary {
            get {
                return ResourceManager.GetString("FieldIsMandary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de nascimento inválida.
        /// </summary>
        public static string InvalidBirthdate {
            get {
                return ResourceManager.GetString("InvalidBirthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Campo inválido {0}..
        /// </summary>
        public static string InvalidField {
            get {
                return ResourceManager.GetString("InvalidField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome inválido.
        /// </summary>
        public static string InvalidPersonName {
            get {
                return ResourceManager.GetString("InvalidPersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Requisição inválida.
        /// </summary>
        public static string InvalidRequest {
            get {
                return ResourceManager.GetString("InvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data da dose da vacinação não pode menor do que a anterior.
        /// </summary>
        public static string InvalidVaccinationDate {
            get {
                return ResourceManager.GetString("InvalidVaccinationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tamanho da página não pode ser negativo.
        /// </summary>
        public static string PageSizeCannotBeNegative {
            get {
                return ResourceManager.GetString("PageSizeCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tamanho da página deve ser menor que {0}.
        /// </summary>
        public static string PageSizeMustBeLowerThan {
            get {
                return ResourceManager.GetString("PageSizeMustBeLowerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código de sexo inválido, consulte a equipe técnica.
        /// </summary>
        public static string PersonGenderIsInvalid {
            get {
                return ResourceManager.GetString("PersonGenderIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome da pessoa é obrigatório.
        /// </summary>
        public static string PersonNameIsRequired {
            get {
                return ResourceManager.GetString("PersonNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pessoa não encontrada.
        /// </summary>
        public static string PersonNotFound {
            get {
                return ResourceManager.GetString("PersonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de vacinação não pode ser maior que a data atual.
        /// </summary>
        public static string VaccinationCannotBeInFuture {
            get {
                return ResourceManager.GetString("VaccinationCannotBeInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dose da vacinação incorreta. Consulte a carteirinha de vacinação.
        /// </summary>
        public static string VaccinationDoseIsWrong {
            get {
                return ResourceManager.GetString("VaccinationDoseIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pessoa ainda não tem vacinação cadastrada para essa vacina. Deve tomar a primeira dose.
        /// </summary>
        public static string VaccinationDoseMustBeFirst {
            get {
                return ResourceManager.GetString("VaccinationDoseMustBeFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dose de vacinação tem que ser maior que zero.
        /// </summary>
        public static string VaccinationDoseMustBeGreatherThanZero {
            get {
                return ResourceManager.GetString("VaccinationDoseMustBeGreatherThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A vacina não possui a dose indicada.
        /// </summary>
        public static string VaccinationDoseNotAllowedForVaccine {
            get {
                return ResourceManager.GetString("VaccinationDoseNotAllowedForVaccine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro de vacinação não encontrado.
        /// </summary>
        public static string VaccinationNotFound {
            get {
                return ResourceManager.GetString("VaccinationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A vacina precisa ter no mínimo uma dose.
        /// </summary>
        public static string VaccineDosesCannotBeZero {
            get {
                return ResourceManager.GetString("VaccineDosesCannotBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome da vacina é obrigatório.
        /// </summary>
        public static string VaccineNameIsRequired {
            get {
                return ResourceManager.GetString("VaccineNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome da vacina não pode exceder 100 caracteres.
        /// </summary>
        public static string VaccineNameIsTooLong {
            get {
                return ResourceManager.GetString("VaccineNameIsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Vacina não encontrada.
        /// </summary>
        public static string VaccineNotFound {
            get {
                return ResourceManager.GetString("VaccineNotFound", resourceCulture);
            }
        }
    }
}
